server {
  # Прослушиваемый порт
  listen 3000;

  # Включение сжатия
  gzip on;
  gzip_types text/html application/javascript application/json text/css;

  # Корневая директория
  root /usr/share/nginx/html;

  # Индексный файл
  index index.html;

  location / {
    # Сначала пытается обслужить запрос в виде файла,
    # если файл не обнаружен то возвращает index.html
    try_files $uri /index.html;
  }

  location ~* ^(/index\.html|/version\.json|/config\.json)$ {
    # Выключение кеширования
    add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
    expires off;
    etag off;
  }
}
