name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  typecheck:
    name: Typecheck
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22.23.2

      - name: Install yarn
        run: npm install --global yarn@1.22.22

      - name: Install dependencies
        run: yarn install --frozen-lockfile 

      - name: Typecheck
        run: yarn typecheck

  deploy:
    name: Deployment
    runs-on: self-hosted
    needs:
      - typecheck
    steps:
      - name: Deploy Application by ID
        uses: thinesjs/dokploy-deployer-action@v1
        with:
            dokploy_url: ${{ secrets.DOKPLOY_URL }}
            api_key: ${{ secrets.DOKPLOY_API_KEY }}
            type: application
            application_id: ${{ secrets.DOKPLOY_APPLICATION_ID }}
            wait_for_deployment: true
